### ISSUE TITLE
Dialog icon size is wrong

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/uitk#233]
Dialog icon size is smaller than expected, see below snapshot.

![Dialog QA Snapshot](https://snapshots.chromatic.com/snapshots/628e27029fcf95004a62cafd-62bb2cb1ad5c05b21eb59d29/capture.png)

https://uitk.pages.dev/?path=/story/lab-dialog-qa--examples-grid

From Chromatic history, it's broken from b71a4d92b7ce32f1823503c42b7e55c03517c6f7

Also, Chromatic is not capturing the full grid, which missed the top most example.

**Comment by joshwooding** [comment]
Fixed in #564
