### ISSUE TITLE
ToolkitProvider

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/uitk#302]
## Preparation
- [x] Existing defect backlog reviewed/evaluated, prioritized, and selected
- [x] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
- [x] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
- [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
- [x] Usability testing plan defined or deemed unnecessary
- [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads
## Development
- [x] Component implemented in/ported to TypeScript
- [x] 3rd-party dependencies removed
- [x] JSS converted to CSS
- [x] CSS upgraded to use characteristics
- [x] Selected defects resolved
- [x] Component API finalized
- [x] Necessary refactoring completed
- [x] Selected enhancements added
## Testing
- [x] Functional test script is implemented in Cypress and passes
- [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
- [x] QA (v1-2 visual regression) test passes
- [x] Automated Axe tests added and pass
## Examples
- [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
## Deployment
- [ ] Codemods for migration created and verified
- [ ] Reviews/Signoff
- [ ] Dev production review
- [ ] Design review
- [ ] Product signoff
- [ ] ADA review
- [x] Documentation
- [x] Dev docs content provided
- [ ] TK1→Odyssey migration guide provided
- [ ] Design docs provided
- [ ] Consolidated documentation produced by combining dev content, migration guide, and design docs
- [ ] Consolidated documentation published on Storybook
- [ ] Consolidated documentation reviewed and updated according to user feedback
- [ ] Figma symbols
- [ ] New Odyssey Figma symbol created
- [ ] Figma symbol references updated to use new Figma symbol

**Comment by origami-z** [comment]
This needs a bit more work, e.g. add mention of breakpoints and relationship with responsive components, and how to consume density/theme/breakpoints using provided `useAbc` hooks we provided

**Comment by maj-stella** [comment]
AriaAnnouncerProvider, which is part of ToolkitProvider, has been tested on Win 10, Chrome 103, NVDA 2019. No issues found.

**Comment by ZarkoPernar** [comment]
@joshwooding what is left on this component? I see design signed off on this in their "Essential Components" status tracker.

**Comment by parsakhan21** [comment]
Had call with Josh to do kick-off. 
Nav to get started on specs - minimal for this. ADA/features etc. 
Touch base with Stella re: ADA
Dev - make sure nothing is missing. DoD still in progress - ensure all is on track.

**Comment by parsakhan21** [comment]
10/26
Nav implemented feedback/updates to specs 
Immanuel and Alina double checking specs 
Stella to check ARIA portion of the spec and provide sign-off

**Comment by parsakhan21** [comment]
10/26
Nav implemented feedback/updates to specs 
Immanuel and Alina double checking specs 
Stella to check ARIA portion of the spec and provide sign-off

**Comment by el-dav** [comment]
As part of this work could we split out the ToolkitContext into different parts e.g. instead of:

```
<ToolkitContext.Provider value={{ density, themes, breakpoints }}>
    <ViewportProvider>{themedChildren}</ViewportProvider>
</ToolkitContext.Provider>
```

could we have:

```
<DensityContext.Provider value={density}>
  <ThemeContext.Provider value={theme}>
    <BreakpointsContext.Provider value={breakpoints}>
      <ViewportProvider>{themedChildren}</ViewportProvider>
    </BreakpointsContext.Provider>
  </ThemeContext.Provider>
</DensityContext.Provider>
```


You would also need update hooks for `useTheme`, `useDensity` and `useBreakpoints`, plus create a separate react context for each.

The reason for this is currently any components where `useTheme` is used will also re-render if density updates in the context and vice versa. Separating the Contexts will prevent this and won't change the API's from the consumer's perspective.

Let me know if this needs more explanation

**Comment by alycrys** [comment]
@el-dav this makes perfect sense to me. Thanks

**Comment by heswell** [comment]
I understand the point, but in actual apps, how often would we expect theme or density to be updated at runtime ? I would have thought very rarely. Thus  are the extra levels of complexity in the component tree every place a Provider is used really worth it ?

**Comment by bhoppers2008** [comment]
Density is unlikely but theme (or at least mode) isn't out of the question. We've just included new icons in the odyssey package to cater for a light/dark toggle.

**Comment by joshwooding** [comment]
I guess the question would be how often we see components "subscribing" to density or theme and not both. I think this will only affect a very small number of users since I would expect most of them to depend on doing it via CSS.

**Comment by el-dav** [comment]
For me I don't really see any disadvantage, The API doesn't change from the user's perspective, and there are no additional elements in the HTML. So even if the advantage is relatively minor it seems worthwhile. 

Plus we can't really assess the full extent of the benefit as a consuming application might use lots of components with density/theme and this could affect them more.

The only disadvantage seems to be extra `<Providers>` in the devtools, but I don't see that as significant.

**Comment by el-dav** [comment]
Incidentally you can hide Contexts/Providers in your react devtools if you want


![Image](https://user-images.githubusercontent.com/7252227/198658408-e958759d-4bbf-4c6b-b34b-6a2fc36189e4.png)

**Comment by heswell** [comment]
I'm going to bow out of this conversation and will respect whatever decision you make.

**Comment by JohannaJoergensen** [comment]
Stella to conduct reviews on Tues, 1 Nov

**Comment by origami-z** [comment]
FYI, there's s still some `uitk-light` mentioned in styling doc.

**Comment by joshwooding** [comment]
> FYI, there's s still some `uitk-light` mentioned in styling doc.

Thanks @origami-z, should be solved now 👍🏽
