### ISSUE TITLE
StatusIndicator

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/uitk#318]
- [x] https://github.com/jpmorganchase/uitk/pull/648
- [x] Interaction Spec
- [ ] Accessibility Spec
- [x] Documentation

**Comment by ZarkoPernar** [comment]
@JoanaMMoreira I c/p the definition of done checklist from confluence but feel free to edit this as you wish since we don't really have a template for these right now.

**Comment by JoanaMMoreira** [comment]
@maj-stella here's the link: https://uitk.pages.dev/?path=/story/core-stateicon--default-state-icon

**Comment by maj-stella** [comment]
An ideal DOM structure would be that <svg> element is a top level element; therefore remove two span elements above svg and add role=“img” and aria-label=“xxx” to the <svg> element directly.

**Comment by JoanaMMoreira** [comment]
> I suggest using aria-label="success" instead of aria-label="success tick" as default value.
> 
> <img alt="Screenshot 2022-09-07 at 15 33 14" width="1032" src="https://user-images.githubusercontent.com/112501956/188923875-056d3172-333b-45a0-9d52-a678314b0be1.png">

@maj-stella here you go: https://state-icon-aria-label.uitk.pages.dev/?path=/story/core-stateicon--all-state-icons

**Comment by joshwooding** [comment]
After a conversation with @jeanlaleuf and @pseys StateIcon should probably be renamed to StatusIcon to match the upcoming status validation work.

**Comment by shinytoyrobots** [comment]
Further consideration - should this be "StatusIndicator" or similar, rather than StatusIcon.

**Comment by JoanaMMoreira** [comment]
> Further consideration - should this be "StatusIndicator" or similar, rather than StatusIcon.

Sure, should we discuss with the team? cc @joshwooding

**Comment by sion-docs** [comment]
Documentation review

- typo 'unterlying'
- Can there be more detail/examples added to the content around passing Custom Props in the Props table?
- Can the order of the different statuses be the same whenever they are listed? The text versions in the status row of the Props table do not match the graphical equivalents under the 'Status icons' heading.
- Include information currently under 'Status icons' under the Features heading. Provide guidance as to when different icons should be used under 'Use when...' .
- Add API, Props and Anatomy content as H3s under a H2 'Configuing StatusIcon' 
- Add Accessibility, Related components, and Help and Support sections

**Comment by joshwooding** [comment]
> > Further consideration - should this be "StatusIndicator" or similar, rather than StatusIcon.
> 
> Sure, should we discuss with the team? cc @joshwooding

Hey, this is fine. It came out of conversations we've had with design and the new indication pattern.

**Comment by JoanaMMoreira** [comment]
@sion-docs thanks for this, here's a draft PR for you to review please: https://github.com/jpmorganchase/uitk/pull/508 
@maj-stella could you please add some wording around accessibility so we can include it in the docs?

**Comment by parsakhan21** [comment]
11/10 

kick-off call tomorrow 11/11 
rename to statusindicator - to be confirmed tomorrow
