### ISSUE TITLE
☂️ Website design (system)

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#518]
We need some _rough_ visual & interaction designs for:

* The overall "outer" page layout - i.e. the stuff that's the same for each page (header, footer, margins, etc.)
* Styles for typography (use whatever Odyssey gives us out of the box, but if there are gaps we need to define those additional styles)
* "Inner", page-specific layouts

While doing this we should be on the lookout for any reusable components / patterns that emerge, so that we can implement them accordingly. (Who knows, they may even become things we eventually contribute back to the core component library!)

Deliverables

* Just enough of a design (wireframe sketch on the back of a napkin, Figma, something inbetween or a bit of everything - whatever is quick to make and sufficient to convey the overarching _direction and intent_ of the design) for developers to begin making a draft implementation
    * We can then iterate and refine the design in the browser by pairing with developers

Requirements

* Page layout must be responsive (let's do [mobile-first](https://bradfrost.com/blog/post/mobile-first-responsive-web-design/))

James's wish list
* Support light/dark mode (via [CSS `prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)) - all the Odyssey components already have both themes, so we may as well. Also, [it's good for accessibility](https://mobilea11y.com/quick-wins/dark-mode/)!

Relates to #483

**Comment by JohannaJoergensen** [comment]
Breakdown to smaller buckets of work

**Comment by james-nash** [comment]
This work is being covered by various other design tasks, so I don't think we need this issue in our backlog anymore. Therefore closing it.
