### ISSUE TITLE
Implement V1 site page template(s) and key components

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#534]
Once the basic setup (#510), IA (#513) and visual design (#518) are ready, we need to start building our site!

It probably makes sense to do this from the outside in, i.e.:

* Setup and create our core styling
    * Hopefully most will be provided by Odyssey itself, but we _may_ need some additional CSS classes for site-specific layout, typography, styles, etc.
* Build whatever top-level page layout(s) we need (header, nav, footer and a big hole in the middle for the per-page content)
* If the design has highlighted the need for some components that get re-used on multiple pages (e.g. stuff for site navigation, sidebars, page footers, etc.) then lets implement those accordingly

Essentially, this issue should cover building all the "stuff" we need to give us an empty shell of a website that's ready to have some content poured into it.

(Relates to #483)

**Comment by JohannaJoergensen** [comment]
We should use "O" components when we can - with a possible mix and match (current plus next gen)

**Comment by james-nash** [comment]
Since we've been making separate issues to cover the dev work for the various pages, I think this issue is now redundant, so I'll close it.
