### ISSUE TITLE
Dev: Setup docusaurus in monorepo

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#547]
Add an out-of-the-box [Docusaurus](https://docusaurus.io/) (as per decision in #548) setup to the `uitk` monorepo.

By the end of this developers should be able to:

* Run the site locally on their machines for development work
* Create a static build of the site that can be deployed somewhere

Note: As part of this task we need to figure out if/how the Docusaurus builds can be integrated with the `modular` build tooling we use for everything else.

**Comment by JohannaJoergensen** [comment]
1 Nov - almost done; waiting for one placeholder page - Eleanor to merge
