### ISSUE TITLE
Dev: Spike: Decide Static Site Generator

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#548]
- Compare Gatsby, Next & Mosaic and decide on which one to use for this 'cupcake' version
- Compare hosting options (e.g. Github pages, AWS, Cloudflare)

Present findings to team with suggested solutions

Make a decision by Tuesday 25th October

**Comment by parsakhan21** [comment]
Working on initial research. Make decisions next week.

**Comment by origami-z** [comment]
Any consideration around higher level frameworks like docusaurus?

**Comment by james-nash** [comment]
We have decided to go with [Docusaurus](https://docusaurus.io/) for now.
