### ISSUE TITLE
Setup site and build & deploy pipeline

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#550]
(Depends on #547)

Need to setup deployments to Cloudflare for the website:

* `main` branch should deploy to the production URL (which is still TBC (see #551) - so a temp URL is fine for now)
* PRs should have preview deploys

**Comment by EleanorHaproff** [comment]
it looks like Cloudflare Bot doesn't support monorepos just yet, (see [here](https://community.cloudflare.com/t/cloudflare-pages-monorepo-with-github-actions/378934)) so I will have to create a github action for this. Looking at implementing something like this https://www.emmanuelgautier.com/blog/monorepo-publish-with-cloudflare-pages

**Comment by JohannaJoergensen** [comment]
1 Nov - Eleanor to begin work

**Comment by origami-z** [comment]
Don't think `main` branch is published?

**Comment by EleanorHaproff** [comment]
> Don't think `main` branch is published?

it's on https://head.uitk-site.pages.dev/
