### ISSUE TITLE
Design: Discovery: Research and Competitor Analysis

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/uitk#554]

**Comment by parsakhan21** [comment]
Looking into competitive websites/design research (layout, navigation,etc)

**Comment by JohannaJoergensen** [comment]
Deadline: Tues, 25 October

**Comment by shey-v** [comment]
Scheduled meeting to present back findings to the team on Thursday, 27 October.

**Comment by shey-v** [comment]
Scheduled meeting to present back findings to the team on Thursday, 27 October.
