### ISSUE TITLE
Design iterations (x 3 examples)

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/uitk#585]
Explore 3 design directions / routes we could possibly go down

**Comment by JohannaJoergensen** [comment]
Shey to continue mockups discussed from last Thurs and Friday's ATD mtgs - will aim to get this done by end of week. Content kickoff mtg scheduled for Tues, 1 Nov

**Comment by shey-v** [comment]
8 Nov - In today's design share meeting Shey presented her initial site design explorations worked on since last week (leveraging master brand, sketchy illustration style, affinity to fintech) and referenced a few other site designs.

- The team agreed on:

1. What works well (dark or mixed themes, bold typography, iconography or illustrations and use of Masterbrand key line) and 
2. What didn’t work well (the gradients, mixing photography) etc.

- We decided on a direction to take forwards and iterate on the “Affinity to fintech - reflecting JP Morgan branding” approach (the last idea shown - using a dark or mixed theme with an iconography style that reflects the master brand, using bold text with no gradients).

- Between tomorrow and next week Shey will work on iterating these designs. This way when the content for the homepage has been reviewed and signed off / shared with the group Shey can drop this in and see how it looks all together.
