### ISSUE TITLE
Initial styling exploration and implementation

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/uitk#596]
Official design specs are incoming via #585, but for now we can start playing around with customising the styling.
- where feasible, use our theme and css variables
- add our Toolkit provider?
- explore [swizzling](https://docusaurus.io/docs/swizzling)
- use our components where possible e.g. Button

**Comment by JohannaJoergensen** [comment]
1 Nov - small issue; tried using Toolkit Provider; will catch up with Eleanor
