### ISSUE TITLE
Iterate on agreed visual design direction

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/uitk#598]
Once design iterations are complete, present back to Robin and Design leads and choose a direction to flow with. 

Can start to collaborate with content to structure each individual page using the visual design angle and ensure key info has 'stand out'.

**Comment by shey-v** [comment]
- Based off of feedback gathered from the team (on 8 Nov) Shey can now start to look at iterating on the design direction chosen. 

- Shey will also take a look at what the exact Masterbrand rules are & look to explore different uses of color and aspects of this within the iterations

- It was mentioned to take a look at the navigation and how this can be structured when more content is eventually dropped in to the site 

- Shey will continue to work on these iterations until next week and arrange to present these back to the design leads / Robin to gather further feedback / sign off 

- Can then start to work with content to drop in the copy and adjust the designs

**Comment by JohannaJoergensen** [comment]
9 Nov - scheduled mtg with design leads for additional feedback
