### ISSUE TITLE
Draft initial copy for getting started page

### ISSUE THREAD

**Issue by JohannaJoergensen** [jpmorganchase/uitk#613]
Need to draft initial copy for "Getting started" page:

- [x] Draft getting started guide for designers - @shey-v
- [x] Draft getting started guide for designers - @james-nash 

Drafts to be submitted to @rufcha & Mitch as MS Word files by **COB Fri, 11 Nov**.

**Comment by JohannaJoergensen** [comment]
4 Nov - will work with Josh to produce dev segment

**Comment by james-nash** [comment]
Draft developer instructions can be seen here: https://fbdaa0a4.uitk-site.pages.dev/docs/getting-started

**Comment by shey-v** [comment]
Copy sent to Rufaro as of 14 Nov, for review.
