### ISSUE TITLE
Explore css/js animations for website

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#633]
- [x] build custom carousel [Update Nov 10: no longer doing this, will have tabs instead]
- [x] animate keyline
- [x] animate svg elements (see floating animation here https://codepen.io/SusanneLundblad/pen/DKRKbN)

**Comment by JoanaMMoreira** [comment]
Draft PR here: https://github.com/jpmorganchase/uitk/pull/647
@shey-v it would be good to catchup to get your thoughts on our initial implementation

**Comment by steveukx** [comment]
11 Nov - Joana/Felicia have draft PR to be reviewed with Shey

**Comment by JoanaMMoreira** [comment]
This has been reviewed with Shey and we will start adding these animations as we build the website. I'll close the draft PR as we don't need to merge in these changes.
