### ISSUE TITLE
Initial homepage implementation

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#670]
- [x] Apply website theme as per specs (colours, fonts, etc)
- [x] Implement custom navbar
- [x] Add content/images to hero section
- [x] Add animations as per #633

**Comment by JohannaJoergensen** [comment]
18 Nov - built navbar and added theme/colors - will open PR

**Comment by JoanaMMoreira** [comment]
Raised a PR here: https://github.com/jpmorganchase/uitk/pull/691 
Link to the latest build: https://5355394f.uitk-site.pages.dev/
