### ISSUE TITLE
Contributions and Support Page

### ISSUE THREAD

**Issue by JohannaJoergensen** [jpmorganchase/uitk#680]
Items featured on this page to be defined by James

**Comment by JoanaMMoreira** [comment]
This is now ready for dev https://www.figma.com/file/fPb1bB30ujVtDJK2MgZZAo/Salt-Design-System---Site?node-id=947%3A92542&t=HC16E4VlHGeZN5ep-0

**Comment by JohannaJoergensen** [comment]
5 Dec - PR has been raised
