### ISSUE TITLE
Figma libraries naming alignment

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/uitk#727]
28 Nov - mtg scheduled with Ben and Paul for input and guidance
- [x] - [ ] Align with components team to rename all Figma libraries from 'Odyssey' to 'Salt' now that name has been confirmed and approved.

**Comment by shey-v** [comment]
28 Nov - Ben / Paul / Shey agreed to update the Figma Library Cover pages and the shared Figma team space to "Salt" rather than "Odyssey". 

Note: We need to align the site docs and the Figma files so that anywhere referencing Odyssey or UITK is updated to 'Salt'. 

Josh / James to agree on final name, i.e. Toolkit Provider >>> Salt Provider. This is pending/TBC based on convo with Josh.

**Comment by joshwooding** [comment]
#737 covers the renaming effort on the dev side

**Comment by JohannaJoergensen** [comment]
2 Dec - The Salt Figma Libraries have been updated with new cover pages. We are just waiting on content/dev to confirm the name for ‘Salt Provider’ i.e. will this have a space within it or not? I can then rename the respective Figma file.
