### ISSUE TITLE
Build clickable cards for the site

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#739]
We've discussed having our current cards clickable and animating on hover, so we need to refine this with design/product and implement the changes (keeping in mind it should still be ADA compliant)

**Comment by JohannaJoergensen** [comment]
1 Dec - work in progress

**Comment by JoanaMMoreira** [comment]
PR ready for review: https://github.com/jpmorganchase/uitk/pull/756
