### ISSUE TITLE
Design and implement the Hamburger menu

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/uitk#745]
- [x] Design and spec out the Hamburger menu to include:

1. New Logo as per AppHeader
2. Github favicon/link
3. Links to all site pages

- [ ] Dev to implement as per spec.

**Comment by shey-v** [comment]
2 Dec - Design spec created, ready for dev.

**Comment by JoanaMMoreira** [comment]
https://github.com/jpmorganchase/uitk/pull/797 has been merged in, will raise a separate PR for further styling tweaks
