### ISSUE TITLE
Getting started refinements

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/uitk#775]
Designing with Salt page
- We want to have 24px above and below imagery
- Ensure there is also 24px spacing underneath all headings
- Only separator needs to have shadow applied to it Shadow/black - L02 token (on design and develop page)
- Fix the table headings to reflect proper densities (currently all says HDs)
- Jo to investigate font weight issue
- Jo to investigate the right-hand nav - line width (4px) and position
- Addition of Figma logo needs to be updated / added 
- Fix imagery to be new one (as per design and SVGs instead of PNGs to avoid pixelation) 
- Reduce the size of the imagery 

 
 
Developing with Salt page
 - See if we can wrap by default ALL code blocks (this will be important for mobile users too). Jo to investigate.
- Switch code block to light theme. 
- Change pink to teal 500 (preference) or purple 500
- Add new key line to accordion and remove hover state, also amend title (View the web fonts, widths and styles) and update the font size as per design mockup we did today.
- Change height between text and code block from 24px to 12px.

 
Footer
- Footer background container height needs to be reduced.
- On mobile, ensure there is 12px spacing between main links and copyright text

**Comment by JohannaJoergensen** [comment]
5 Dec - nearly done; will raise PR
