### ISSUE TITLE
Write blog post outlining Salt release - rationale, narrative, roadmap

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/uitk#836]
Initially for internal publication, prior to development of longer term public blogging solution. Must align with Salt release.

**Comment by shinytoyrobots** [comment]
Draft content for this is nearly complete and signed-off.

Blog is Wordpress driven, correct? Who has access to post - so we can schedule this to coincide to release. @james-nash @rufcha ?

**Comment by rufcha** [comment]
Hi @shinytoyrobots, Yes, we use WordPress. Paul and I usually publish the posts. Once Tanya/Mitch have signed it off, I'm happy to do a final review to check for styling etc, and then create the post.

**Comment by JohannaJoergensen** [comment]
12 Dec - pending review by content and comms

**Comment by shinytoyrobots** [comment]
@pseys - we should schedule this to go live (or send live manually) to coincide with the site going live.
