### ISSUE TITLE
Fix minor a11y bugs on site

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#856]
* The "Start using Salt" button on the homepage is currently marked up as `<a hef="..."><button>...</button></a>`, which is invalid HTML and also an a11y issue since you can't nest interactive elements like that. I should just be a link (since it navigates to another page), but a link _styled_ to look like a button.
* The homepage does not wrap it's main contents in a `<main>` element (all the other pages do though, so we must be doing something weird on the homepage only). It needs to as this element acts as a landmark that screenreaders use to let users quickly navigate there.

**Comment by JoanaMMoreira** [comment]
PR is open: https://github.com/jpmorganchase/uitk/pull/867
