### ISSUE TITLE
Site: Footer styling

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/uitk#861]
* The padding on the page footer looks a little tight - especially on mobile screens
* The keylines between the text are using the wrong color token. They should be "Separable / Secondary / Border"
* On narrow widths (or with an enlarged default font size), the line height on the links looks too big:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/16718916/206818849-e1bde5bf-d954-4339-b76a-deb08e8d492a.png">

**Comment by JohannaJoergensen** [comment]
13 Dec - PR raised; pending review
